version: '3.8'
services:
  backend:
    build: backend/
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - backend/.env

  frontend:
    build: frontend/
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - frontend/.env
