version: '3.8'
services:
  backend:
    image: anubislord2109/task-manager-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - backend/.env

  frontend:
    image: anubislord2109/task-manager-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - frontend/.env
