version: '3.8'
services:
  backend:
    image: anubislord2109/task-manager-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://anubis:admin@cluster0.k2oin.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

  frontend:
    image: anubislord2109/task-manager-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://18.207.218.68:5000
