---
apiVersion: v1
kind: Namespace
metadata:
  name: task-manager
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: task-manager
  name: task-manager-config
data:
  port: "5000"
  NODE_ENV: "production"
  REACT_APP_API_URL: "http://localhost:5000"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: task-manager
  name: task-manager-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://anubis:admin@cluster0.k2oin.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
