apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: test-env-backend
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: test-env-backend
  template:
    metadata:
      labels:
        app: test-env-backend
    spec:
      containers:
        - name: backend
          image: anubislord2109/task-manager-backend:test
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: test-env-config
                  key: port
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: test-env-secret
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: backend-service
spec:
  selector:
    app.kubernetes.io/name: test-env-backend
  ports:
    - name: backend-port
      port: 5000
      targetPort: 5000
      nodePort: 31546
  type: NodePort
