---
apiVersion: v1
kind: Namespace
metadata:
  name: task-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task-manager
  name: deployment
spec:
  selector:
    matchLabels: 
     app.kubernetes.io/name: task-manager
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: task-manager
    spec:
      containers:
        - name: backend
          image: anubislord2109/task-manager-backend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
        - name: frontend
          image: anubislord2109/task-manager-frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: task-manager
  name: forntend-service
spec:
  selector:
    app.kubernetes.io/name: task-manager
  ports:
    - name: frontend-port
      port: 80
      targetPort: 80
      nodePort: 30371
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  namespace: task-manager
  name: backed-service
spec:
  selector:
    app.kubernetes.io/name: task-manager
  ports:
    - name: backend-port
      port: 5000
      targetPort: 5000
      nodePort: 31546
  type: NodePort

